server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

spring:
  application:
    name: config-service

  rabbitmq:
    host: localhost
    port: 5672

  cloud:
    config:
      server:
        git:
          uri: https://oauth2:exLQD6KWgaZA32EUayiy@lab.ssafy.com/s11-final/S11P31C103.git
          search-paths: Backend/application-config
          default-label: develop


---
spring:
  config:
    activate:
      on-profile: deploy

  rabbitmq:
    host: k11c103.p.ssafy.io
    port: 5672