server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

spring:
  application:
    name: config-service

  rabbitmq:
    host: localhost
    port: 5672

  profiles:
    active: native