server:
  port: 0

spring:
  application:
    name: diary-service

  rabbitmq:
    host: localhost
    port: 5672

  datasource:
    diary:
      jdbc-url: jdbc:h2:mem:~/DiaryServiceApplication
      username: sa
      password:
    users:
      jdbc-url: jdbc:mysql://k11c103.p.ssafy.io:3306/ddasoom?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      username: ddasoom
      password: ssafygwangjuc103
  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka